### ISSUE TITLE
obras +18 não aparecem na busca

### ISSUE THREAD

**Issue by Tomo-kun** [OneDefauter/MangaDex-Upload#1]
conteudos +18 não aparencem na busca

![2024-11-12 19 20 18 localhost 7e1c3034a8d0](https://github.com/user-attachments/assets/8eeff0a2-4c2e-4dfd-9077-57ef254cf8e5)

**Comment by OneDefauter** [comment]
Desculpa pela demora em responder.

Foi corrigido na versão v1.0.5

**Comment by Tomo-kun** [comment]
Vlw One
